### ISSUE TITLE
Can't install the package.

### ISSUE THREAD

**Issue by lvian** [b01/d3#1]
Hello there,

Decided to give a try to your package today but I couldn't install it. Composer returns an error telling it can't find the required package "kshabazz/slib ~1.1 -> no matching package found". Did you gave up on this package?  The only package using related to you on packagist is the D3 one.

**Comment by b01** [comment]
@Ivian Hi,

Thanks for giving my library a try. I am still actively developing it. The slib it is looking for is on github [https://github.com/b01/slib/tree/1.1.2](here) as well, but not released on packagist. 

Unfortunately I do not know why composer cannot find it. Can you try running composer with -vvv for more output details, maybe it is looking in the wrong place for the slib repo.

**Comment by lvian** [comment]
Hi @b01 

Menaged to make it work.

I was forced to add this to my project composer.json

```
"repositories": [
        {
                "type": "vcs",
                "url": "https://github.com/b01/d3.git"
        },
        {
            "type": "vcs",
                "url": "https://github.com/b01/slib.git"
        }],
```

Without that composer just wouldn't install your library. I did this on a fresh project after downloading the latest composer, so I don't think its a project or composer problem. 

bye

**Comment by b01** [comment]
I see. I was under the impression that if I had that section in the d3 composer.json, then others that require d3 would not need to add it to their own composer.json. I need to read up on how that works. I will also make the slib library available on packagist, which should eliminate the need to add that.
